CREATE DATABASE userDB;

CREATE TABLE usert(
    user_id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    datacriacao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);